config/routes.rb
Rails.application.routes.draw do
  resources :race_cages
  resources :motherhood_cages do
    resources :mother_rabbits, only: [:new, :index]
  end
  resources :weaning_cages
  resources :cages do
    resources :mother_rabbits,  only: [:new, :index]
    resources :race_rabbits,    only: [:new, :index]
    resources :weaning_rabbits, only: [:new, :index]
  end
  resources :fattening_cages
  resources :compartments
  resources :farms
  resources :weights
  resources :pregnancies
  resources :rabbits do
    resources :weights, only: [:new, :index]
    resources :pregnancies, only: [:new, :index]
    resources :cages do
      resources :compartments do
        collection do
          get :available
        end
        member do
          put :move
        end
      end
      collection do
        get :available
      end
      member do
        put :move
      end
    end
    member do
      put :kill
      get :new_birth
      post :birth
      get :new_conception
      post :conception
      get :edit_notes
    end
    collection do
      get :multiple_kill
      resources :cages do
        collection do
          get :available_for_group
        end
        member do
          put :move
          put :move_for_group
        end
      end
    end
  end
  resources :mother_rabbits
  resources :baby_rabbits
  resources :race_rabbits
  resources :weaning_rabbits
  resources :fattening_rabbits
  resources :rabbits
  devise_for :users

  root 'cages#index'

end

app/models/rabbit.rb
class Rabbit < ActiveRecord::Base

  belongs_to :container, polymorphic: true

  has_many :weights

  belongs_to :pregnancy

  validates :gender,     inclusion: { in: ["male", "female", "unknown"] }, allow_nil: true
  validates :birth_date, presence: true
  validate  :validate_cage

  # delegate :cage, to: :compartment, prefix: true
#  delegate :value, to: :weights, prefix: true
  delegate :mother, to: :pregnancy

  after_initialize :default_values

  scope :mothers,    -> { where(type: "MotherRabbit") }
  scope :fattening,  -> { where(type: "FatteningRabbit") }
  scope :race,       -> { where(type: "RaceRabbit") }
  scope :babies,     -> { where(type: "BabyRabbit") }
  scope :weaning,    -> { where(type: "WeaningRabbit") }

  MIN_AGE = 0
  MAX_AGE = 100000

  def self.min_age
    MIN_AGE
  end

  def self.max_age
    MAX_AGE
  end

  def self.accept_gender? gender
    true
  end

  def self.accept_age? age
    logger.info "age > #{self.min_age} && age < #{self.max_age}"
    age > self.min_age && age < self.max_age
  end

  def can_become_classes
    c_b_c = []

    [MotherRabbit, FatteningRabbit, RaceRabbit, BabyRabbit, WeaningRabbit].each do |rabbit_class|
      puts "go fo #{rabbit_class}"
      if rabbit_class.accept_age?(self.age) && rabbit_class.accept_gender?(self.gender)
        puts "YESS!"
        c_b_c << rabbit_class
      end
    end

    c_b_c
  end

  def age
    birth_date ? (Date.today - birth_date).to_i : 0
  end

  def last_weight
    weights.first.try(:value)
  end

  def cage
    if self.container.kind_of? Cage
      self.container
    elsif self.container.kind_of? Compartment
      self.container.cage
    end
  end

  def default_values
    self.birth_date ||= Date.today
  end

  def name_or_position
    self.name.present? ? self.name : "Coniglio in #{self.position}"
  end

  def position
    "#{self.cage.code}"
  end

  def kill death_date = Date.today
    self.update_attributes(
      death_date: death_date || Date.today,
      container_id: nil,
      container_type: nil
    )
  end

  def move new_cage, new_compartment
    self.update_attributes(container_id: new_cage.id, container_type: new_cage.type, type: "WeaningRabbit")
  end

  def mother?
    false
  end

  def baby_rabbit?
    false
  end

  def editable_fields
    [
      "container_type",
      "container_id",
      "type",
      "name",
      "birth_date",
      "gender",
      "notes"
    ]
  end

  def list_item_heading
    name
  end

  def list_item_text
    if self.last_weight.nil?
      "Nessun peso registrato"
    else
      "#{last_weight} Kg #{self.weights.last.days_from_registration} giorni fa"
    end
  end

  def secondary_infos
    infos = {}

    if self.last_weight.present?
      infos[:weight] = "#{self.last_weight} Kg"
    else
      infos[:weight] = "Nessun peso"
    end

    infos
  end

  protected
    def set_name_by_cage
      if self.name_changed? && self.cage.name != self.name
        self.cage.update_attributes(name: self.name)
      end

      if self.container_id_changed? && self.container_id && self.cage.name != self.name
        self.update_attributes(name: self.cage.name)
      end
    end

    def validate_cage
      puts "self.class #{self.class}"
      if cage && !cage.kind_of?(self.class.allowed_cage_type)
        self.errors.add(:cage, "deve essere una #{self.class.allowed_cage_type.model_name.human}")
      end
    end


end

app/controllers/rabbits_controller.rb
class RabbitsController < ApplicationController
  before_filter :authenticate_user!#, except: [:index]


  before_action :set_rabbit, only: [:show, :edit, :update, :destroy, :kill, :birth, :new_birth, :new_conception, :conception, :edit_notes, :available_cages, :move]
  before_action :set_cage,   only: [:show, :edit, :new, :index, :kill, :destroy, :new_birth, :new_conception, :conception, :edit_notes, :available_cages, :move, :multiple_kill]

  before_filter :set_rabbit_type

  # GET /rabbits
  # GET /rabbits.json
  def index
    @rabbits = Rabbit.all
  end

  # GET /rabbits/1
  # GET /rabbits/1.json
  def show
    @weights = @rabbit.weights.order("registered_on DESC")
  end

   # GET /rabbits/new
  def new
    if params[:container_id].present? && params[:container_type].present?
      container_id   = params[:container_id]
      container_type = params[:container_type]
    else
      container_id   = @cage.id
      container_type = "Cage"
    end
    @rabbit = Rabbit.new(
      type: class_name_by_controller,
      container_id: container_id,
      container_type: container_type
    )
  end

  # GET /rabbits/1/edit
  def edit
    @fields = params[:fields]
  end

  # POST /rabbits
  # POST /rabbits.json
  def create
    @rabbit = Rabbit.new(rabbit_params)
    puts @rabbit.to_yaml
    @cage   = @rabbit.cage

    respond_to do |format|
      if @rabbit.save
        format.html { redirect_to rabbit_path(@rabbit), notice: 'Coniglio creato con successo.' }
        format.json { render :show, status: :created, location: @rabbit }
      else
        flash[:error] =  @rabbit.errors.full_messages.to_sentence
        format.html { render :new }
        format.json { render json: @rabbit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rabbits/1
  # PATCH/PUT /rabbits/1.json
  def update
    respond_to do |format|
      if @rabbit.update(rabbit_params)
        format.html { redirect_to @rabbit, notice: 'Coniglio aggiornato con succcesso.' }
        format.json { render :show, status: :ok, location: @rabbit }
      else
        format.html { render :edit }
        format.json { render json: @rabbit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rabbits/1
  # DELETE /rabbits/1.json
  def destroy
    @rabbit.destroy
    respond_to do |format|
      format.html { redirect_to cage_path(@cage), notice: 'Coniglio elimiato con successo.' }
      format.json { head :no_content }
    end
  end

  def kill
    @rabbit.kill params[:death_date]

    respond_to do |format|
      format.html { redirect_to cage_path(@cage), notice: "Registrata uccisione del coniglio"}
    end
  end

  def multiple_kill
    @rabbits = Rabbit.where(id: params[:rabbits_ids])
    result   = true
    error_at = 0

    @rabbits.each_with_index do |rabbit, i|
      error_at = i
      result &&= rabbit.kill(Date.today)
      puts "result => #{result}"
    end

    if result
      respond_to do |format|
        format.html { redirect_to cage_path(@cage), notice: "Morti registrate con successo"}
      end
    else
      flash[:error] =  @rabbits[error_at].errors.full_messages.to_sentence
      respond_to do |format|
        format.html { redirect_to cage_path(@cage) }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rabbit
      @rabbit = Rabbit.find(params[:id])
    end

    def set_cage
      if @rabbit.present?
        @cage = @rabbit.cage
      else
        @cage = Cage.find(params[:cage_id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rabbit_params
      params.require(class_instance_name_by_controller.to_sym).
        permit(:name, :container_id, :container_type, :type, :gender, :notes, :birth_date, :death_date)
    end

    def set_rabbit_type
      @rabbit_type = class_instance_name_by_controller
    end


end

app/views/rabbits/_form.html.erb
<%

if !defined?(fields) || fields.blank?
  fields = rabbit.editable_fields
end

 %>

<%= bootstrap_form_for(rabbit) do |f| %>
  <% fields.each do |field| %>
    <% if field == "birth_date" || field == "death_date" %>
      <%= f.date_select field, use_month_numbers: true, start_year: 1.year.ago.year, end_year: 1.year.from_now.year, default: Date.today %>
    <% elsif field == "name" %>
      <%= f.text_field field %>
    <% elsif field == "gender" %>
      <%= f.select :gender, [["Sconosciuto", "unknown"], ["Maschio", "male"], ["Femmina", "female"]] %>
    <% elsif field == "notes" %>
      <%= f.text_area :notes %>
    <% elsif field.in?(["container_type", "container_id", "type"]) %>
      <%= f.hidden_field field %>
    <% end %>
  <% end %>
  <%#= render "#{rabbit.model_name.route_key}/fields", rabbit: rabbit, f: f, fields: fields %>
  <%= f.submit nil, class: "btn btn-primary btn-raised btn-lg btn-block" %>
<% end %>

app/views/rabbits/_list.html.erb
<%= bootstrap_form_tag(url: "javascript:void(0)", method: "GET", html: { id: "multiselect" }) do %>
  <%= hidden_field_tag :cage_id, cage.id %>

  <div class="list-group rabbits">

    <% rabbits.each_with_index do |rabbit, index| %>
      <% if rabbit %>
        <%= link_to rabbit_path(rabbit), class: "list-group-item link-item",  id: "rabbit-#{rabbit.id}-link", data: { rabbit_id: rabbit.id } do %>
          <div class="row-action-primary row-action-gender-<%= rabbit.gender %>">
            <i class="code"><%= index + 1 %></i>
          </div>
          <div class="row-content">
            <div class="action-secondary"><i class="material-icons">chevron_right</i></div>
            <!-- <div class="least-content">15m</div> -->
            <h4 class="list-group-item-heading"><%= pluralize(rabbit.age, "giorno", "giorni") %></h4>


            <% if rabbit.last_weight.present? %>
              <p class="list-group-item-text"><%= number_with_precision rabbit.last_weight, precision: 3 %> Kg</p>
            <% else %>
              <p class="list-group-item-text">Nessun peso registrato</p>
            <% end %>
          </div>
        <% end %>

        <label class="list-group-item checkbox-item" id="rabbit-<%= rabbit.id %>-checkbox">
          <div class="row-action-primary checkbox">
            <label>
              <%= check_box_tag 'rabbits_ids[]', rabbit.id -%>
              <span class="checkbox-material">
                <span class="check"></span>
             </span>
            </label>
          </div>
          <div class="row-content">
            <h4 class="list-group-item-heading"><%= pluralize(rabbit.age, "giorno", "giorni") %></h4>
            <p class="list-group-item-text">Nessun peso registrato</p>
          </div>
        </label>
      <% end %>
    <% end %>
  </div>
  <%= submit_tag "Sposta", class: "btn btn-primary btn-raised btn-lg btn-block btn-multiselect", data: { action: available_for_group_cages_path} %>
  <%= submit_tag "Registra morte", class: "btn btn-primary btn-raised btn-lg btn-block btn-multiselect", data: { action: multiple_kill_rabbits_path } %>
<% end %>

<% content_for :bottom_js do %>
  <script type="text/javascript">
    $("#multiselect input[type='submit']").on("click", function(e){
      e.preventDefault()
      console.log("ciao" + $(this).data("action"))

      $(this).closest("form").attr("action", $(this).data("action")).submit();
    })
  </script>
<% end %>

app/views/rabbits/_nav.html.erb
<% content_for :nav_left do  %>
	<% if @rabbit.kind_of? RaceRabbit %>
  	<li><%= icon_link_to "arrow_back", cages_path %></li>
	<% else %>
  	<li><%= icon_link_to "arrow_back", cage_path(rabbit.cage) %></li>
	<% end %>
<% end %>
<% content_for :nav_right do  %>
  <li class="dropdown">
    <%= icon_link_to "more_vert", "#", class: "dropdown-toggle", data: { toggle: "dropdown" } %>
    <ul class="dropdown-menu">
      <li><%= link_to "Modifica", edit_rabbit_path(rabbit) %></li>
      <li><%= link_to "Elimina", rabbit_path(rabbit), :method => :delete, data: { confirm: "Sicuro di voler eliminare questo coniglio?" } %></li>
    </ul>
  </li>
<% end %>

app/views/rabbits/available_cages.html.erb
<% content_for :nav_left do  %>
  <li><%= icon_link_to "arrow_back", rabbit_path(@rabbit) %></li>
<% end %>

<h1>Scegli la Gabbia</h1>

<%= render "cages/move_list", cages: @fattening_cages,  rabbit: @rabbit %>
<%= render "cages/move_list", cages: @motherhood_cages, rabbit: @rabbit %>
<%= render "cages/move_list", cages: @weaning_cages,    rabbit: @rabbit %>
<%= render "cages/move_list", cages: @race_cages,       rabbit: @rabbit %>

app/views/rabbits/available_cages_for_group.html.erb
<% content_for :nav_left do  %>
  <li><%= icon_link_to "arrow_back", cage_path(@cage) %></li>
<% end %>

<h1>Scegli la Gabbia</h1>

<%= render "cages/move_list", cages: @fattening_cages,  rabbits: @rabbits %>
<%= render "cages/move_list", cages: @motherhood_cages, rabbits: @rabbits %>
<%= render "cages/move_list", cages: @weaning_cages,    rabbits: @rabbits %>
<%= render "cages/move_list", cages: @race_cages,       rabbits: @rabbits %>

app/views/rabbits/edit.html.erb
<% content_for :nav_left do  %>
  <li><%= icon_link_to "arrow_back", rabbit_path(@rabbit) %></li>
<% end %>

<h1>Modifica <%= @rabbit.name_or_position %></h1>

<%= render 'form', rabbit: @rabbit, fields: @fields %>

app/views/rabbits/edit_notes.html.erb
<% content_for :nav_left do  %>
  <li><%= icon_link_to "arrow_back", rabbit_path(@rabbit) %></li>
<% end %>


<h1>Note per <%= @rabbit.name_or_position %></h1>

<%= bootstrap_form_for(@rabbit) do |f| %>
  <%= f.text_area :notes %>
  <%= f.submit nil, class: "btn btn-primary btn-raised btn-lg btn-block" %>
<% end %>

app/views/rabbits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Rabbits</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rabbits.each do |rabbit| %>
      <tr>
        <td><%= link_to 'Show', rabbit %></td>
        <td><%= link_to 'Edit', edit_rabbit_path(rabbit) %></td>
        <td><%= link_to 'Destroy', rabbit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_rabbit_path, class: "btn btn-primary btn-fab btn-bottom btn-right" do %>
  <%= fa_icon "plus" %>
<% end %>

app/views/rabbits/new.html.erb
<% content_for :nav_left do  %>
  <li><%= icon_link_to "arrow_back", cage_path(@cage) %></li>
<% end %>

<h1>Nuovo <%= @rabbit.model_name.human %></h1>

<%= render 'form', rabbit: @rabbit %>

app/views/rabbits/new_birth.html.erb
<% content_for :nav_left do  %>
  <li><%= icon_link_to "arrow_back", rabbit_path(@rabbit) %></li>
<% end %>

<h1>Registra Parto</h1>

<%= bootstrap_form_tag url: birth_rabbit_path(@rabbit), method: "POST" do |f|  %>
  <%= f.number_field :size, min: 1, required: true %>
  <%= f.date_select :birth_date, use_month_numbers: true, start_year: 1.year.ago.year, end_year: 1.year.from_now.year, default: Date.today %>
  <%= f.submit "Registra", class: "btn btn-primary btn-raised btn-lg btn-block" %>
<% end %>

app/views/rabbits/new_conception.html.erb
<% content_for :nav_left do  %>
  <li><%= icon_link_to "arrow_back", rabbit_path(@rabbit) %></li>
<% end %>

<h1>Registra Concepimento</h1>

<%= bootstrap_form_tag url: conception_rabbit_path(@rabbit), method: "POST" do |f|  %>
  <% if @conceptioners.size > 1 %>
    <%= f.select_tag :conceptioner_id, options_for_select(@conceptioners, :id, :position) %>
  <% elsif @conceptioners.size == 1 %>
    <%= f.hidden_field :conceptioner_id, value: @conceptioners.first.id %>
  <% end %>
  <%= f.date_select :conceptioned_on, use_month_numbers: true, start_year: 1.year.ago.year, end_year: 1.year.from_now.year, default: Date.today %>
  <%= f.submit "Registra", class: "btn btn-primary btn-raised btn-lg btn-block" %>
<% end %>

app/views/rabbits/show.html.erb
<%= render "rabbits/nav", rabbit: @rabbit %>

<h1><%= @rabbit.name_or_position %></h1>


<div class="list-group rabbit-details">
  <a href="<%= edit_rabbit_path(@rabbit, fields: [:birth_date]) %>" class="list-group-item">
    <div class="row-content">
      <h4 class="list-group-item-heading">Età</h4>
      <div class="least-content"><%= @rabbit.age %> giorni</div>
      <div class="action-secondary"><i class="material-icons">chevron_right</i></div>
    </div>
  </a>
  <div class="list-group-separator"></div>
  <%= link_to edit_rabbit_path(@rabbit, fields: [:gender]), class: "list-group-item", disabled: !@rabbit.editable_fields.include?("gender") do %>
    <div class="row-content">
      <h4 class="list-group-item-heading">Sesso</h4>
      <div class="least-content"><%= t("gender.#{@rabbit.gender || "unknown"}") %></div>
      <div class="action-secondary"><i class="material-icons">chevron_right</i></div>
    </div>
  <% end %>
  <div class="list-group-separator"></div>
  <a href="<%= rabbit_weights_path(@rabbit) %>" class="list-group-item">
    <div class="row-content">
      <h4 class="list-group-item-heading">Peso</h4>
      <div class="least-content"><%= @rabbit.last_weight ? "#{@rabbit.last_weight} kg" : "Nessuno" %></div>
      <div class="action-secondary"><i class="material-icons">chevron_right</i></div>
    </div>
  </a>
  <div class="list-group-separator"></div>
  <% if @rabbit.mother? %>
    <% if @rabbit.pregnant? %>
      <a href="<%= edit_pregnancy_path(@rabbit.in_progress_pregnancy) %>" class="list-group-item">
        <div class="row-content">
          <h4 class="list-group-item-heading">Incinta da</h4>
          <div class="least-content"><%= @rabbit.in_progress_pregnancy.days_from_start %> giorni</div>
          <div class="action-secondary"><i class="material-icons">chevron_right</i></div>
        </div>
      </a>
      <div class="list-group-separator"></div>
    <% end %>
    <a href="<%= rabbit_pregnancies_path(@rabbit) %>" class="list-group-item">
      <div class="row-content">
        <h4 class="list-group-item-heading">Gravidanze concluse</h4>
        <div class="least-content"><%= @rabbit.pregnancies.completed.size %></div>
        <div class="action-secondary"><i class="material-icons">chevron_right</i></div>
      </div>
    </a>
    <div class="list-group-separator"></div>
  <% end %>
  <a href="<%= edit_rabbit_path(@rabbit, fields: [:notes]) %>" class="list-group-item">
    <div class="row-content">
      <h4 class="list-group-item-heading">Note</h4>
      <p class="list-group-item-text notes"><%= @rabbit.notes.to_s %></p>
      <div class="action-secondary"><i class="material-icons">chevron_right</i></div>
    </div>
  </a>
  <div class="list-group-separator"></div>
  <% if @rabbit.pregnancy.try(:mother) %>
    <div class="list-group-item">
      <div class="row-content">
        <h4 class="list-group-item-heading">Madre</h4>
        <p class="list-group-item-text notes"><%= @rabbit.pregnancy.mother.name %></p>
        <!-- <div class="action-secondary"><i class="material-icons">chevron_right</i></div> -->
      </div>
    </div>
    <div class="list-group-separator"></div>
  <% end %>
</div>

<% if @rabbit.mother? %>
  <% if !@rabbit.pregnant? %>
    <%= link_to "Ingravida", new_rabbit_pregnancy_path(@rabbit), class: "btn btn-primary btn-block btn-lg" %>
  <% end %>
<% end %>
<%= link_to "Pesa", new_rabbit_weight_path(@rabbit), class: "btn btn-primary btn-block btn-lg" %>
<%= link_to "Sposta", available_rabbit_cages_path(@rabbit), class: "btn btn-primary btn-block btn-lg" %>
<%= link_to "Pronto", kill_rabbit_path(@rabbit), method: :put, class: "btn btn-primary btn-block btn-lg", data: { confirm: "I conigli non ritornano più in vita"} %>
<%= link_to "Registra morte", kill_rabbit_path(@rabbit), method: :put, class: "btn btn-primary btn-block btn-lg", data: { confirm: "I conigli non ritornano più in vita"} %>