config/routes.rb
Rails.application.routes.draw do
  resources :race_cages
  resources :motherhood_cages do
    resources :mother_rabbits, only: [:new, :index]
  end
  resources :weaning_cages
  resources :cages do
    resources :mother_rabbits,  only: [:new, :index]
    resources :race_rabbits,    only: [:new, :index]
    resources :weaning_rabbits, only: [:new, :index]
  end
  resources :fattening_cages
  resources :compartments
  resources :farms
  resources :weights
  resources :pregnancies
  resources :rabbits do
    resources :weights, only: [:new, :index]
    resources :pregnancies, only: [:new, :index]
    resources :cages do
      resources :compartments do
        collection do
          get :available
        end
        member do
          put :move
        end
      end
      collection do
        get :available
      end
      member do
        put :move
      end
    end
    member do
      put :kill
      get :new_birth
      post :birth
      get :new_conception
      post :conception
      get :edit_notes
    end
    collection do
      get :multiple_kill
      resources :cages do
        collection do
          get :available_for_group
        end
        member do
          put :move
          put :move_for_group
        end
      end
    end
  end
  resources :mother_rabbits
  resources :baby_rabbits
  resources :race_rabbits
  resources :weaning_rabbits
  resources :fattening_rabbits
  resources :rabbits
  devise_for :users

  root 'cages#index'

end

app/models/pregnancy.rb
class Pregnancy < ActiveRecord::Base

  default_scope { order("starting_at DESC") }

  validates :starting_at, presence: true
  validates :rabbit_id, presence: true

  validate :starting_before_ending
  validate :avoid_intersections

  belongs_to :rabbit
  has_many :rabbits, dependent: :destroy

  scope :completed,   -> { where.not(ending_at: nil) }
  scope :in_progress, -> { where(ending_at: nil) }

  after_save :update_rabbits_birth_date

  def editable_fields
    ["starting_at", "ending_at", "rabbit_id", "rabbits_size"]
  end

  def in_progress?
    ending_at.nil?
  end

  def days_from_start
    (Date.today - starting_at).to_i
  end

  def mother
    self.rabbit
  end

  def rabbits_size
    self.rabbits.size
  end

  def rabbits_size=rabbits_size
    # return if rabbits_size.to_i != rabbits_size.to_i

    diff = rabbits_size.to_i - self.rabbits.size

    if diff < 0

      self.rabbits.destroy(self.rabbits.limit(diff.abs))
    elsif diff > 0

      ((self.rabbits.size + 1)..(self.rabbits.size + diff)).each do |r|
        logger.info { "add baby rabbit! #{r}" }

        br = BabyRabbit.new(
          pregnancy_id: self.id,
          birth_date: self.ending_at,
          container_id: self.rabbit.container_id,
          container_type: self.rabbit.container_type
        )

        self.rabbits << br

        # self.rabbits.babies.new(
        # )
      end
    end
    puts "self.rabbits => #{self.rabbits.first}"
  end

  private
    def update_rabbits_birth_date
      puts "self.ending_at_changed? => #{self.ending_at_changed?}"
      self.rabbits.update_all(birth_date: self.ending_at) if self.ending_at_changed?
    end

    def starting_before_ending
      if self.starting_at_changed? && self.ending_at && self.starting_at > self.ending_at
        self.errors.add(:starting_at, "deve essere prima della data di conclusione")
      end
      if self.ending_at && self.ending_at_changed? && self.starting_at > self.ending_at
        self.errors.add(:ending_at, "deve essere dopo data di inizio")
      end
    end

    def avoid_intersections
      pregnancies = self.rabbit.pregnancies.where.not(id: self.id)

      if pregnancies.where("starting_at < ? AND (ending_at > ? OR ending_at IS NULL)", self.starting_at, self.starting_at).any?
        self.errors.add(:starting_at, "non può essere durante un'altra gravidanza")
      elsif self.ending_at && pregnancies.where("starting_at < ? AND (ending_at > ? OR ending_at IS NULL)", self.ending_at, self.ending_at).any?
        self.errors.add(:ending_at, "non può essere durante un'altra gravidanza")
      end
    end

end

app/controllers/pregnancies_controller.rb
class PregnanciesController < ApplicationController
  before_filter :authenticate_user!#, except: [:index]

  before_action :set_pregnancy, only: [:show, :edit, :update, :destroy]
  before_action :set_rabbit, only: [:show, :edit, :new, :index, :destroy, :update]
  before_action :set_cage, only: [:show, :edit, :new, :index, :destroy, :update]


  # GET /pregnancies
  # GET /pregnancies.json
  def index
    @pregnancies = @rabbit.pregnancies
  end

  # GET /pregnancies/1
  # GET /pregnancies/1.json
  def show
  end

  # GET /pregnancies/new
  def new
    @pregnancy = @rabbit.pregnancies.new(starting_at: Date.today)
  end

  # GET /pregnancies/1/edit
  def edit
    @fields = params[:fields]
  end

  # POST /pregnancies
  # POST /pregnancies.json
  def create
    @pregnancy = Pregnancy.new(pregnancy_params)
    @rabbit    = @pregnancy.rabbit
    @cage      = @rabbit.cage

    respond_to do |format|
      if @pregnancy.save
        format.html { redirect_to rabbit_pregnancies_path(@rabbit), notice: 'Inizio gravidanza registrato' }
        format.json { render :show, status: :created, location: @pregnancy }
      else
        format.html { render :new }
        format.json { render json: @pregnancy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pregnancies/1
  # PATCH/PUT /pregnancies/1.json
  def update
    respond_to do |format|
      puts "pregnancy_params => #{pregnancy_params}"
      if @pregnancy.update(pregnancy_params)
        format.html { redirect_to rabbit_pregnancies_path(@rabbit), notice: 'Gravidanza aggiornata con successo.' }
        format.json { render :show, status: :ok, location: @pregnancy }
      else
        format.html { render :edit }
        format.json { render json: @pregnancy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pregnancies/1
  # DELETE /pregnancies/1.json
  def destroy
    @pregnancy.destroy
    respond_to do |format|
      format.html { redirect_to rabbit_pregnancies_path(@rabbit), notice: 'Gravidanza rimossa con successo' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pregnancy
      @pregnancy = Pregnancy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pregnancy_params
      params.require(:pregnancy).permit(:starting_at, :ending_at, :rabbit_id, :rabbits_size)
    end

    def set_rabbit
      if @pregnancy
        @rabbit = @pregnancy.rabbit
      else
        @rabbit = Rabbit.find(params[:rabbit_id])
      end
    end

    def set_cage
      @cage = @rabbit.cage
    end

end

app/helpers/pregnancies_helper.rb
module PregnanciesHelper
end

app/views/pregnancies/_form.html.erb
<%
  if !defined?(fields) || fields.blank?
    fields = pregnancy.editable_fields
  end


  end_disabled = pregnancy.in_progress? || pregnancy.new_record?

 %>

<%= bootstrap_form_for(pregnancy) do |f| %>

  <% fields.each do |field| %>
    <% if field.in?(["starting_at"]) %>
      <%= f.date_select field, use_month_numbers: true, start_year: 1.year.ago.year, end_year: 1.year.from_now.year, default: Date.today %>
      <% if end_disabled %>
        <%#= f.check_box :in_progress? %>
        <div class="form-group">
          <div class="checkbox">
            <label>
              <input type="checkbox" id="complete_pregnancy">
              <span class="checkbox-material"><span class="check"></span></span> Registra nascita
            </label>
          </div>
        </div>
      <% end %>
    <% elsif field.in?(["ending_at"]) %>
      <div class="disable-in-progress <%= "disabled" if pregnancy.in_progress? %>">
        <%= f.date_select field, use_month_numbers: true, start_year: 1.year.ago.year, end_year: 1.year.from_now.year, default: pregnancy.starting_at + 1.month, disabled: end_disabled %>
      </div>
    <% elsif field.in?(["rabbit_id"]) %>
      <%= f.hidden_field field %>
    <% elsif field.in?(["rabbits_size"]) %>
      <div class="disable-in-progress <%= "disabled" if pregnancy.in_progress? %>">
        <%= f.number_field field, disabled: end_disabled %>
      </div>
    <% end %>
  <% end %>

  <%= f.submit nil, class: "btn btn-primary btn-raised btn-lg btn-block" %>
<% end %>

<script type="text/javascript">
  $("#complete_pregnancy").on("click", function() {
    var checked = $(this).prop("checked")

    console.log("checked => " + checked)

    $(".disable-in-progress").toggleClass("disabled")
    $(".disable-in-progress select, .disable-in-progress input, .disable-in-progress textarea, .disable-in-progress button").prop("disabled", !checked)
  });
</script>

app/views/pregnancies/edit.html.erb
<% content_for :nav_left do  %>
  <li><%= icon_link_to "arrow_back", rabbit_pregnancies_path(@rabbit) %></li>
<% end %>
<% content_for :nav_right do  %>
  <li><%= icon_link_to "delete", pregnancy_path(@pregnancy), :method => :delete, data: { confirm: "Vuoi eliminare questa Gravidanza? Tutti gli eventuali figli saranno eliminati." } %></li>
<% end %>


<h1>Modifica Gravidanza</h1>

<%= render 'form', pregnancy: @pregnancy, fields: @fields %>

app/views/pregnancies/index.html.erb
<% content_for :nav_left do  %>
  <li><%= icon_link_to "arrow_back", rabbit_path(@rabbit) %></li>
<% end %>

<h1>Gravidanze per <%= @rabbit.name_or_position %></h1>

<%= icon_link_to "add", new_rabbit_pregnancy_path(@rabbit), class: "btn btn-primary btn-fab btn-raised btn-block add-weight" %>

<table class="table table-hover table-clickable-row">
  <thead>
    <tr>
      <th>Fine Gravidanza</th>
      <th>Cuccioli</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% if @pregnancies.empty? %>
      <tr>
        <td colspan="3">Nessuna gravidanza registrata</td>
      </tr>
    <% else %>
      <% @pregnancies.each do |pregnancy| %>
        <tr>
          <% if pregnancy.in_progress? %>
            <td>In corso, iniziata <%= pregnancy.days_from_start %> giorni fa</td>
            <td></td>
          <% else %>
            <td><%= pregnancy.ending_at.strftime("%d/%m") %></td>
            <td><%= pregnancy.rabbits.size %></td>
          <% end %>
          <td><%= icon_link_to "chevron_right", edit_pregnancy_path(pregnancy) %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/pregnancies/new.html.erb
<% content_for :nav_left do  %>
  <li><%= icon_link_to "arrow_back", rabbit_path(@rabbit) %></li>
<% end %>

<h1>Nuova Gravidanza</h1>

<%= render 'form', pregnancy: @pregnancy %>

app/views/pregnancies/show.html.erb
<p>
  <strong>Starting at:</strong>
  <%= @pregnancy.starting_at %>
</p>

<p>
  <strong>Ending at:</strong>
  <%= @pregnancy.ending_at %>
</p>

<p>
  <strong>Rabbit:</strong>
  <%= @pregnancy.rabbit_id %>
</p>

<%= link_to 'Edit', edit_pregnancy_path(@pregnancy) %> |
<%= link_to 'Back', pregnancies_path %>