config/routes.rb
Rails.application.routes.draw do
  resources :race_cages
  resources :motherhood_cages do
    resources :mother_rabbits, only: [:new, :index]
  end
  resources :weaning_cages
  resources :cages do
    resources :mother_rabbits,  only: [:new, :index]
    resources :race_rabbits,    only: [:new, :index]
    resources :weaning_rabbits, only: [:new, :index]
  end
  resources :fattening_cages
  resources :compartments
  resources :farms
  resources :weights
  resources :pregnancies
  resources :rabbits do
    resources :weights, only: [:new, :index]
    resources :pregnancies, only: [:new, :index]
    resources :cages do
      resources :compartments do
        collection do
          get :available
        end
        member do
          put :move
        end
      end
      collection do
        get :available
      end
      member do
        put :move
      end
    end
    member do
      put :kill
      get :new_birth
      post :birth
      get :new_conception
      post :conception
      get :edit_notes
    end
    collection do
      get :multiple_kill
      resources :cages do
        collection do
          get :available_for_group
        end
        member do
          put :move
          put :move_for_group
        end
      end
    end
  end
  resources :mother_rabbits
  resources :baby_rabbits
  resources :race_rabbits
  resources :weaning_rabbits
  resources :fattening_rabbits
  resources :rabbits
  devise_for :users

  root 'cages#index'

end

app/models/race_cage.rb
class RaceCage < Cage

  validate :only_one_rabbit

  has_many :rabbits, as: :container

  def rabbit
  	self.rabbits.first
  end

  def list_item_text
    if self.rabbit
    	self.rabbit.list_item_text
    else
      ""
    end
  end

  def list_item_heading
    if self.rabbit
    	self.rabbit.list_item_heading
    else
      "Vuota"
    end
  end


  private
    def only_one_rabbit
      if self.rabbits.size > 1
        self.errors.add(:base, "Questa gabbia può avere solo un coniglio")
      end
    end
end

app/controllers/race_cages_controller.rb
class RaceCagesController < CagesController

  # GET /cages/1
  # GET /cages/1.json
  def show
  	if @cage.rabbit
    	redirect_to rabbit_path(@cage.rabbit)
  	else
    	render "#{@cage.model_name.route_key}/show"
  	end
  end

end

app/helpers/race_cages_helper.rb
module RaceCagesHelper
end

app/views/race_cages/_list.html.erb
<div class="list-group">
  <% cages.each do |cage| %>
    <%= link_to cage_path(cage), class: "list-group-item" do %>
      <div class="row-action-primary row-action-<%= cage.model_name.element %>">
        <i class="cage"><%= cage.code %></i>
      </div>
      <div class="row-content">
        <div class="action-secondary"><i class="material-icons">chevron_right</i></div>
        <!-- <div class="least-content">15m</div> -->
        <h4 class="list-group-item-heading"><%= cage.rabbits.size %> conigli</h4>

        <p class="list-group-item-text">Altri dati</p>
      </div>
    <% end %>
  <% end %>
</div>

app/views/race_cages/show.html.erb
<% content_for :nav_left do  %>
  <li><%= icon_link_to "arrow_back", cages_path(anchor: "race_cages") %></li>
<% end %>
<% content_for :nav_right do  %>
  <li class="dropdown">
    <%= icon_link_to "more_vert", "#", class: "dropdown-toggle", data: { toggle: "dropdown" } %>
    <ul class="dropdown-menu">
      <li><%= link_to "Aggiungi Coniglio", new_cage_race_rabbit_path(@cage) %></li>
      <li><%= link_to "Modifica Gabbia", edit_cage_path(@cage) %></li>
      <li><%= link_to "Elimina Gabbia", cage_path(@cage), :method => :delete, data: { confirm: "Sicuro di voler eliminare questa Gabbia?" } %></li>
    </ul>
  </li>
<% end %>

<h1>Gabbia <%= @cage.code %></h1>