config/routes.rb
Rails.application.routes.draw do
  resources :race_cages
  resources :motherhood_cages do
    resources :mother_rabbits, only: [:new, :index]
  end
  resources :weaning_cages
  resources :cages do
    resources :mother_rabbits,  only: [:new, :index]
    resources :race_rabbits,    only: [:new, :index]
    resources :weaning_rabbits, only: [:new, :index]
  end
  resources :fattening_cages
  resources :compartments
  resources :farms
  resources :weights
  resources :pregnancies
  resources :rabbits do
    resources :weights, only: [:new, :index]
    resources :pregnancies, only: [:new, :index]
    resources :cages do
      resources :compartments do
        collection do
          get :available
        end
        member do
          put :move
        end
      end
      collection do
        get :available
      end
      member do
        put :move
      end
    end
    member do
      put :kill
      get :new_birth
      post :birth
      get :new_conception
      post :conception
      get :edit_notes
    end
    collection do
      get :multiple_kill
      resources :cages do
        collection do
          get :available_for_group
        end
        member do
          put :move
          put :move_for_group
        end
      end
    end
  end
  resources :mother_rabbits
  resources :baby_rabbits
  resources :race_rabbits
  resources :weaning_rabbits
  resources :fattening_rabbits
  resources :rabbits
  devise_for :users

  root 'cages#index'

end

app/models/weight.rb
class Weight < ActiveRecord::Base
  default_scope { order(registered_on: :desc) }

  belongs_to :rabbit

  validates :value,     presence: true, numericality: { greater_than: 0 }
  validates :registered_on, uniqueness: { scope: :rabbit_id, message: "Peso già registrato in questa data" }

  def days_from_registration
    (Date.today - registered_on).to_i
  end


end

app/controllers/weights_controller.rb
class WeightsController < ApplicationController
  before_filter :authenticate_user!#, except: [:index]


  before_action :set_weight, only: [:show, :edit, :update, :destroy]
  before_action :set_rabbit, only: [:show, :edit, :new, :index, :destroy, :update]
  before_action :set_cage, only: [:show, :edit, :new, :index, :destroy, :update]


  # GET /weights
  # GET /weights.json
  def index
    @weights = @rabbit.weights
  end

  # GET /weights/1
  # GET /weights/1.json
  def show
  end

  # GET /weights/new
  def new
    @weight = @rabbit.weights.new(registered_on: Date.today, value: @rabbit.last_weight)
  end

  # GET /weights/1/edit
  def edit
  end

  # POST /weights
  # POST /weights.json
  def create
    @weight = Weight.new(weight_params)
    # Already present weight? Update it!
    @rabbit = @weight.rabbit
    @cage   = @rabbit.cage

    # already present weight on this date? update it
    present_weight = @rabbit.weights.where(registered_on: @weight.registered_on).first
    if present_weight
      present_weight.value = @weight.value
      @weight              = present_weight
    end

    respond_to do |format|
      if @weight.save

        format.html { redirect_to rabbit_weights_path(@weight.rabbit), notice: 'Peso registrato con successo.' }
        format.json { render :show, status: :created, location: @weight }
      else
        format.html { render :new }
        format.json { render json: @weight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weights/1
  # PATCH/PUT /weights/1.json
  def update
    respond_to do |format|
      if @weight.update(weight_params)
        format.html { redirect_to rabbit_weights_path(@rabbit), notice: 'Peso aggiornato con successo.' }
        format.json { render :show, status: :ok, location: @weight }
      else
        format.html { render :edit }
        format.json { render json: @weight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weights/1
  # DELETE /weights/1.json
  def destroy
    @weight.destroy
    respond_to do |format|
      format.html { redirect_to rabbit_weights_path(@rabbit), notice: "Peso cancellato con successo" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weight
      @weight = Weight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def weight_params
      params.require(:weight).permit(:rabbit_id, :value, :registered_on)
    end

    def set_rabbit
      if @weight
        @rabbit = @weight.rabbit
      else
        @rabbit = Rabbit.find(params[:rabbit_id])
      end
    end

    def set_cage
      @cage = @rabbit.cage
    end
end

app/views/weights/_form.html.erb
<%= bootstrap_form_for(weight) do |f| %>


  <%= f.hidden_field :rabbit_id %>
  <%= f.date_select :registered_on, use_month_numbers: true, start_year: 1.year.ago.year, end_year: 1.year.from_now.year, default: Date.today %>
  <%= f.number_field :value, step: "any", append: "Kg" %>

  <%= f.submit nil, class: "btn btn-primary btn-block btn-lg" %>
<% end %>

app/views/weights/edit.html.erb
<% content_for :nav_left do  %>
  <li><%= icon_link_to "arrow_back", rabbit_weights_path(@rabbit) %></li>
<% end %>
<% content_for :nav_right do  %>
  <li><%= icon_link_to "delete", weight_path(@weight), :method => :delete, data: { confirm: "Sicuro di voler eliminare questo Peso?" } %></li>
<% end %>


<h1>Modifica Peso</h1>

<%= render 'form', weight: @weight %>

app/views/weights/index.html.erb
<% content_for :nav_left do  %>
  <li><%= icon_link_to "arrow_back", rabbit_path(@rabbit) %></li>
<% end %>

<h1>Pesi per <%= @rabbit.name_or_position %></h1>

<%= icon_link_to "add", new_rabbit_weight_path(@rabbit), class: "btn btn-primary btn-fab btn-raised btn-block add-weight" %>


<table class="table table-hover table-clickable-row">
  <thead>
    <tr>
      <th>Data</th>
      <th>Peso (Kg)</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% if @weights.empty? %>
      <tr>
        <td colspan="3">Nessun peso registrato</td>
      </tr>
    <% else %>
      <% @weights.each do |weight| %>
        <tr>
          <td><%= weight.registered_on.strftime("%d/%m") %> <small class="age">(<%= (weight.registered_on - @rabbit.birth_date).to_i %> giorni)</small></td>
          <td><%= number_with_precision(weight.value, precision: 3) %></td>
          <td class="icon-column"><%= icon_link_to "chevron_right", edit_weight_path(weight) %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/weights/new.html.erb
<% content_for :nav_left do  %>
  <li><%= icon_link_to "arrow_back", rabbit_path(@rabbit) %></li>
<% end %>

<h1>Nuovo Peso</h1>

<%= render 'form', weight: @weight %>

app/views/weights/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_weight_path(@weight) %> |
<%= link_to 'Back', weights_path %>